

= Choreophy SAGA Pattern and Event Sourcing Pattern Project
:toc:

== Getting started 

=== Install Java 11

	brew tap AdoptOpenJDK/openjdk
	brew cask install adoptopenjdk11
	which java
	
=== Instal Maven3

 	brew install maven
 	mvn --version
	

=== SpringToolSuite4/Eclipse Plugins (Optional)

https://marketplace.eclipse.org/content/asciidoctor-editor

Optional: +
https://marketplace.eclipse.org/content/yaml-editor

=== Install Lombok

download available from: https://projectlombok.org

	java -jar lombok.jar

== Build each service using Maven

. Run applications:

	mvn spring-boot:run


== Create Queues in RabbitMQ

. Run RabbitMQ 

	rabbitmq-server 

. Open the web interface of RabbitMQ at http://localhost:15672/#/queues 
. Create the following queues:

* orderCreated
* stockUpdated
* outOfStock	

== Test application

=== Create Stock Items 
1.	First populate the stock with 100 items of aspirin
  
	curl --location --request PUT 'http://localhost:8081/stock' \
	--header 'Content-Type: application/json' \
	--data-raw '{
	        "sku": "123_aspirin",
	        "amount": "100",
	        "branchId": "Paulista"
	    }'
	    
    
2. Then do the same for 200 items of ibuprofen 

	curl --location --request PUT 'http://localhost:8081/stock' \
	--header 'Content-Type: application/json' \
	--data-raw '{
	        "sku": "456_ibuprofen",
	        "amount": "200",
	        "branchId": "Brooklin"
	    }'


    
=== Create Orders

. Create an order with 10 items of aspirin and 10 items of ibuprofen

	curl --location --request POST 'http://localhost:8080/orders' \
	--header 'Content-Type: application/json' \
	--data-raw '{
	        "orderId": "5555",
	        "customerId": "11111",
	        "walletId": "101010",
	        "orderItems":[
	        	{
	        	"sku": "123_aspirin",
	        	"amount": "10",
	        	"branchId": "Paulista",
	        	"cost": "100"
	        	},{
	        	"sku": "456_ibuprofen",
	        	"amount": "10",
	        	"branchId": "Brooklin",
	        	"cost": "50"
	        	}
	        ]
	    }'


. The order status returned should be "*APPROVAL_PENDING*".

. Now find the order

	curl --location --request GET 'http://localhost:8080/orders/5555' \
	--header 'Content-Type: application/json' \
	--data-raw ''


. The order status returned should be "*APPROVED*".

. Create a second order with 200 items of aspirin and 10 items of ibuprofen

	curl --location --request POST 'http://localhost:8080/orders' \
	--header 'Content-Type: application/json' \
	--data-raw '{
	        "orderId": "7777",
	        "customerId": "11111",
	        "walletId": "101010",
	        "orderItems":[
	        	{
	        	"sku": "123_aspirin",
	        	"amount": "200",
	        	"branchId": "Paulista",
	        	"cost": "100"
	        	},{
	        	"sku": "456_ibuprofen",
	        	"amount": "10",
	        	"branchId": "Brooklin",
	        	"cost": "50"
	        	}
	        ]
	    }'

 
. Find the second order

	curl --location --request GET 'http://localhost:8080/orders/7777' \
	--header 'Content-Type: application/json' \
	--data-raw ''


. The returned status should be "*REJECTED*".

== Spring Boot and H2 Magic

. H2 provides a web interface called H2 Console to see the data. Let’s enable h2 console in the `application.properties`.

	spring.h2.console.enabled=true

When you reload the application, you can launch up H2 Console at http://localhost:8080/h2-console.

CAUTION: If you are unable to see the tables... + 
Usually, the table’s are created but the url used in H2 GUI Console is wrong. Change the database url to *jdbc:h2:mem:testdb*
