ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Choreophy SAGA Pattern and Event Sourcing Pattern Project
:toc:


== Getting started 

=== Install Java 11

	brew tap AdoptOpenJDK/openjdk
	brew cask install adoptopenjdk11
	which java
	
=== Instal Maven3

 	brew install maven
 	mvn --version
	

=== SpringToolSuite4/Eclipse Plugins (Optional)

https://marketplace.eclipse.org/content/asciidoctor-editor

Optional: +
https://marketplace.eclipse.org/content/yaml-editor

=== Install Lombok

download available from: https://projectlombok.org

	java -jar lombok.jar
	
	
	
	
== Generating a client code from an OpenAPI specification
	
. To create a client library for the *Order* and *OrderItem* entities, in the order project folder run:

	mvn clean verify -P java-client
	

What does the above command do and how does it work?
[%collapsible]	
====

*******

It generates a java code using a custom profile called “java-client” during integration-test phase. 

How does it work?	

In pom.xml file there is a Maven profile with the openapi-generator-maven-plugin. This profile also overrides the configuration for the the existing spring-boot-maven-plugin.

Spring-boot-maven-plugin is used to temporarily launch the application through maven, while openapi-generator-maven-plugin will retrieve the OpenAPI specification from its endpoint (http://localhost:8080/v2/api-docs) to generate the desired Java code.
	The OpenAPI specification in the mentioned endpoint is generated thanks to Springfox project, which is a tool that serves as a bridge between Spring applications and Swagger by creating a Swagger documentation for certain Spring beans and annotations.


The code generation is done during the integration-test phase in the custom “java-client” profile, so that it can be executed by invoking Maven’s verify phase (invoking just integration-test will not work as we will also need the pre- and post- phases).
	
Spring-boot-maven-plugin is overriden, as it is important to make sure that the application is running when the openapi-generator-maven-plugin‘s goal is executed. That way, the application will be started before the integration-test phase begins and stopped after it finishes.
Setting up openapi-generator-maven-plugin itself, however, is a little bit more complicated. Firstly, this plugin’s default phase is generate-sources, which means that it would run before the specification file is available. That is why the phase is explicitly set as integration-test.

*******

====
{nbsp} +

[start=2]
. The generated client code is inside _/target/generated-sources/java_. To compile, package the generated client code and add its artifact to local maven repository run:

	mvn clean install -f ./target/generated-sources/java -Dmaven.javadoc.skip=true 
	
NOTE: Now it is possible to use the entities Order and OrderItem as a dependency in the stock service.




== Create Queues in RabbitMQ

. Run RabbitMQ 

	rabbitmq-server 

. Open the web interface of RabbitMQ at http://localhost:15672/#/queues 
. Create the following queues:

* orderCreated
* stockUpdated
* outOfStock	



== Build each service using Maven

. Run applications:

	mvn spring-boot:run


== Test application

=== Create Stock Items 
1.	First, fill the stock with 100 items of aspirin
  
	curl --location --request PUT 'http://localhost:8081/stock' \
	--header 'Content-Type: application/json' \
	--data-raw '{
	        "sku": "123_aspirin",
	        "amount": "100",
	        "branchId": "1212"
	    }'
	    
    
2. Then do the same with 200 items of ibuprofen 

	curl --location --request PUT 'http://localhost:8081/stock' \
	--header 'Content-Type: application/json' \
	--data-raw '{
	        "sku": "456_ibuprofen",
	        "amount": "200",
	        "branchId": "1212"
	    }'


    
=== Create Orders

. Create an order with 10 items of aspirin and 10 items of ibuprofen

	curl --location --request POST 'http://localhost:8080/orders' \
	--header 'Content-Type: application/json' \
	--data-raw '{
	        "orderId": "5555",
	        "customerId": "11111",
	        "walletId": "101010",
	        "orderItems":[
	        	{
	        	"sku": "123_aspirin",
	        	"amount": "10",
	        	"branchId": "1212",
	        	"cost": "100"
	        	},{
	        	"sku": "456_ibuprofen",
	        	"amount": "10",
	        	"branchId": "1212",
	        	"cost": "50"
	        	}
	        ]
	    }'


. The order status returned should be "*APPROVAL_PENDING*".

. Now find the order by its id

	curl --location --request GET 'http://localhost:8080/orders/5555' \
	--header 'Content-Type: application/json' \
	--data-raw ''


. The order status returned should be "*APPROVED*".

. Create a second order with 200 items of aspirin and 10 items of ibuprofen

	curl --location --request POST 'http://localhost:8080/orders' \
	--header 'Content-Type: application/json' \
	--data-raw '{
	        "orderId": "7777",
	        "customerId": "11111",
	        "walletId": "101010",
	        "orderItems":[
	        	{
	        	"sku": "123_aspirin",
	        	"amount": "200",
	        	"branchId": "1212",
	        	"cost": "100"
	        	},{
	        	"sku": "456_ibuprofen",
	        	"amount": "10",
	        	"branchId": "1212",
	        	"cost": "50"
	        	}
	        ]
	    }'

 
. Find the second order

	curl --location --request GET 'http://localhost:8080/orders/7777' \
	--header 'Content-Type: application/json' \
	--data-raw ''


. The returned status should be "*REJECTED*".

=== Check Stock

. First, execute all the steps in <<Create Stock Items>>  and <<Create Orders>>. Then fill the stock with 100 items of aspirin at the _1010_ branch 
  
	curl --location --request PUT 'http://localhost:8081/stock' \
	--header 'Content-Type: application/json' \
	--data-raw '{
	        "sku": "123_aspirin",
	        "amount": "100",
	        "branchId": "1010"
	    }'

. Now check the stock for the _123_aspirin_ SKU
	
	curl --location --request GET 'http://localhost:8081/stock/123_aspirin' \
	--header 'Content-Type: application/json' \
	--data-raw ''

. The response should be

	[
	    {
	        "sku": "123_aspirin",
	        "amount": 90,
	        "branchId": "1212"
	    },
	    {
	        "sku": "123_aspirin",
	        "amount": 100,
	        "branchId": "1010"
	    }
	]
	
. To check the stock for the SKU _123_aspirin_ at the _1212_ branch

	curl --location --request GET 'http://localhost:8081/stock/123_aspirin?branches=1212' \
	--header 'Content-Type: application/json' \
	--data-raw ''
	
. The result should be

	[
	    {
	        "sku": "123_aspirin",
	        "amount": 90,
	        "branchId": "1212"
	    }
	]

. Finally, check for all SKUs in stock at the _1212_ and _1010_ branches 
	
	curl --location --request GET 'http://localhost:8081/stock?branches=1010,1212' \
	--header 'Content-Type: application/json' \
	--data-raw ''

. It should be

	[
	    {
	        "sku": "123_aspirin",
	        "amount": 100,
	        "branchId": "1010"
	    },
	    {
	        "sku": "123_aspirin",
	        "amount": 90,
	        "branchId": "1212"
	    },
	    {
	        "sku": "456_ibuprofen",
	        "amount": 190,
	        "branchId": "1212"
	    }
	]

== Spring Boot and H2 Magic

. H2 provides a web interface called H2 Console to see the data. Let’s enable h2 console in the `application.properties`.

	spring.h2.console.enabled=true

When you reload the application, you can launch up H2 Consoles at http://localhost:8080/h2-console (order) and http://localhost:8081/h2-console (stock).

CAUTION: If you are unable to see the tables... + 
Usually, the table’s are created but the url used in H2 GUI Console is wrong. Change the database url to *jdbc:h2:mem:testdb*
